export enum Types {
  LOAD_QUESTIONS_REQUEST = '@QUIZ_ACTION/LOAD_QUESTIONS_REQUEST',
  LOAD_QUESTIONS_SUCCESS = '@QUIZ_ACTION/LOAD_QUESTIONS_SUCCESS',
  LOAD_QUESTIONS_FAILURE = '@QUIZ_ACTION/LOAD_QUESTIONS_FAILURE',

  UPDATE_QUESTION = '@QUIZ_ACTION/UPDATE_QUESTION',

  UPDATE_QUESTION_INDEX = '@QUIZ_ACTION/UPDATE_QUESTION_INDEX',

  UPDATE_QUESTION_ANSWER = '@QUIZ_ACTION/UPDATE_QUESTION_ANSWER',

  UPDATE_CORRECT_ANSWERS_COUNT = '@QUIZ_ACTION/UPDATE_CORRECT_ANSWERS_COUNT',

  RESET_QUIZ = '@QUIZ_ACTION/RESET_QUIZ',
}
